version: '3'
volumes:
  redis:

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
    environment:
      - REDIS_URL=redis://redis:6379
  redis:
    image: "redis:alpine"
    volumes:
      - redis:/data
